# This file provides instructions for packaging.

`Devel-PL_origargv`
	deps:runtime-requirement  [ deps:on "perl 5.006"^^deps:CpanId ];
	deps:test-requirement     [ deps:on "Test::More 0.61"^^deps:CpanId ].

